background {
    monitor =
    path = /home/Vsad/Downloads/jpg
    blur_passes = 2
    blur_size = 6
    noise = 0.01
    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.2
    vibrancy_darkness = 0.5
}

label {
    monitor =
    text = Vsad
    font_size = 48
    font_family = Maple Mono NF
    color = 000000
    position = 0, 60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    outline_color = 0x1a1a2e
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    dots_color = 0xff0000
    inner_color = 0x050505
    font_color = 0xff0000
    fade_on_empty = true
    fade_timeout = 500
    hide_input = false
    placeholder_text =
    position = 0, -20
    halign = center
    valign = center
}
